CREATE OR REPLACE PROCEDURE compraDetalle_insert (
	   codigocompraVar COMPRADETALLE.CODIGOCOMPRA%TYPE,
	   codigoarticuloVar COMPRADETALLE.CODIGOARTICULO%TYPE,
       cantidadcompraVar COMPRADETALLE.CANTIDADCOMPRA%TYPE,
       MONTOCOSTOVar COMPRADETALLE.MONTOCOSTO%TYPE,
       fechaVencimientoVar COMPRADETALLE.fechaVencimiento%TYPE,
       P_RESULT OUT VARCHAR2)
AS

BEGIN

INSERT INTO COMPRADETALLE  
    (CODIGOCOMPRA, CODIGOARTICULO, CANTIDADCOMPRA, MONTOCOSTO, fechaVencimiento)
    VALUES (codigocompraVar,codigoarticuloVar, cantidadcompraVar, MONTOCOSTOVar, fechaVencimientoVar);

COMMIT;  
END;
/