CREATE OR REPLACE PROCEDURE  VALIDAR_USUARIO_PRC
(P_USUARIO IN USUARIO.USUARIO%TYPE,
P_NOMBRE IN USUARIO.NOMBRE%TYPE,
P_CONTRASENA IN USUARIO.CONTRASENA%TYPE,
P_RESULTS OUT NUMBER)
IS
BEGIN
SELECT COUNT(*) INTO P_RESULTS FROM USUARIO WHERE USUARIO=P_USUARIO
AND (CONTRASENA=P_CONTRASENA);
END VALIDAR_USUARIO_PRC;