SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE  VALIDAR_USUARIO_PRC
(P_USUARIO IN USUARIO.USUARIO%TYPE,
P_NOMBRE IN USUARIO.NOMBRE%TYPE,
P_CONTRASENA IN USUARIO.CONTRASENA%TYPE,
P_RESULT OUT VARCHAR2)
IS
BEGIN
SELECT USUARIO, CONTRASENA FROM USUARIO WHERE USUARIO=P_USUARIO
AND CONTRASENA=P_CONTRASENA;
DBMS_OUTPUT.PUT_LINE( P_RESULT);
END VALIDAR_USUARIO_PRC;