CREATE OR REPLACE PROCEDURE ventaDetalle_insert (
	   codigoventavar VENTADETALLE.CODIGOVENTA%TYPE,
	   codigoarticulovar VENTADETALLE.CODIGOARTICULO%TYPE,
       cantidadVar VENTADETALLE.CANTIDAD%TYPE,
       preciovar VENTADETALLE.PRECIO%TYPE,
       P_RESULT OUT VARCHAR2)
AS

BEGIN

INSERT INTO VENTADETALLE  
    (CODIGOVENTA, CODIGOARTICULO, PRECIO, CANTIDAD)
    VALUES (codigoventavar,codigoarticulovar, preciovar, cantidadVar);
    
update ARTICULOEXISTENCIA set EXISTENCIA = (EXISTENCIA - cantidadVar) where CODIGOARTICULO = codigoarticulovar;

P_RESULT := 'Correcto';  

EXCEPTION
  WHEN OTHERS THEN
    P_RESULT := SQLCODE || SQLERRM;  


COMMIT;  
END;
/
